name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome_message
              run: echo "My First commit message"
        
            - name: list files
              run: ls
            
            - name: read files
              run: cat README.md
              
            